# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d870f205a52c69cd4c20d2c2de88a80502870358503edbd5499cf0085e52b6265ef6f5af7486f70fa2c07048f337d0865ccb23bb76a7ba08d1dd146743aac3ba

test:
  secret_key_base: 3d06256969dd3e6a6c94091a9284e459b15ffc1648dcce02c7f414111c69a2fcac4155f812dc28222f489d332bb5f5caea330cd60621ca6b20ca203550d2e433

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
